/**
 * Compile the fixtures under every pinned TypeScript version and write the
 * results table into README.md.
 *
 *     node scripts/run-matrix.mjs            # run and rewrite the README table
 *     node scripts/run-matrix.mjs --check    # fail if the README is out of date
 *
 * **The table is the artifact, and it is generated.** A hand-maintained matrix
 * is wrong the first time a compiler changes and nobody notices, which is the
 * failure this repository exists to document.
 *
 * A case "keeps the narrowing" when compiling its line produces no error. The
 * only error that counts is TS18047 / TS2339 on the narrowed binding itself;
 * anything else means the fixture is broken rather than the case failing, so it
 * is surfaced loudly instead of being scored.
 */
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';

/** Line number → what that line is testing. Must match the fixtures. */
const CASES = {
  'cases/subjects.ts': {
    7: ['module `const`', 'function declaration'],
    8: ['module `const`', 'arrow'],
    9: ['module `const`', 'function expression'],
    10: ['module `const`', '`var`-assigned expression'],
    11: ['module `const`', 'inline callback'],
    12: ['module `const`', 'IIFE'],
    18: ['module `let`', 'function declaration'],
    19: ['module `let`', 'arrow'],
    20: ['module `let`', 'function expression'],
    21: ['module `let`', 'inline callback'],
    27: ['parameter', 'function declaration'],
    28: ['parameter', 'arrow'],
  },
  'cases/scopes.ts': {
    12: ["TS 5.4's own example", 'arrow (control)'],
    19: ['function-scope `let`', 'function declaration'],
    20: ['function-scope `let`', 'arrow'],
    28: ['module `const`', 'arrow (baseline)'],
  },
};

/** Oldest first. 5.3 → 5.4 is the boundary the release notes claim. */
const VERSIONS = ['5.2.2', '5.3.3', '5.4.5', '5.5.4', '5.6.3', '5.7.3', '5.8.3', '5.9.3'];

const TSC_ARGS = [
  '--noEmit', '--strict',
  '--target', 'es2020', '--module', 'esnext',
  '--moduleResolution', 'bundler', '--lib', 'dom,es2020',
];

/** Errors that mean "this case lost the narrowing" rather than "fixture broke". */
const NARROWING_ERRORS = /error (TS18047|TS2339|TS18048|TS2532)/;

function compile(version, file) {
  let out = '';
  try {
    out = execFileSync('npx', ['-y', '-p', `typescript@${version}`, 'tsc', ...TSC_ARGS, file], {
      encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'], shell: process.platform === 'win32',
    });
  } catch (err) {
    // tsc exits non-zero when it reports errors, which is the normal path here.
    out = `${err.stdout ?? ''}${err.stderr ?? ''}`;
  }
  const failed = new Set();
  const unexpected = [];
  for (const line of out.split('\n')) {
    const m = line.match(/\((\d+),\d+\): (error .*)/);
    if (!m) continue;
    if (NARROWING_ERRORS.test(m[2])) failed.add(Number(m[1]));
    else unexpected.push(line.trim());
  }
  return { failed, unexpected };
}

const results = {};
for (const version of VERSIONS) {
  results[version] = {};
  for (const [file, cases] of Object.entries(CASES)) {
    const { failed, unexpected } = compile(version, file);
    if (unexpected.length) {
      console.error(`\n! ${file} on ${version} reported errors that are not narrowing failures:`);
      for (const u of unexpected) console.error(`    ${u}`);
      console.error('  The fixture is broken. Fix it before trusting the table.\n');
      process.exit(2);
    }
    for (const line of Object.keys(cases)) {
      results[version][`${file}:${line}`] = !failed.has(Number(line));
    }
    process.stderr.write('.');
  }
}
process.stderr.write('\n');

/* ------------------------------------------------------------------- table */

const rows = [];
for (const [file, cases] of Object.entries(CASES)) {
  for (const [line, [subject, form]] of Object.entries(cases)) {
    rows.push({
      subject, form,
      cells: VERSIONS.map((v) => results[v][`${file}:${line}`]),
      where: `${file}:${line}`,
    });
  }
}

const head = `| Narrowed binding | Consuming function | ${VERSIONS.map((v) => v.split('.').slice(0, 2).join('.')).join(' | ')} |`;
const sep = `|---|---|${VERSIONS.map(() => '---').join('|')}|`;
const body = rows
  .map((r) => `| ${r.subject} | ${r.form} | ${r.cells.map((ok) => (ok ? '✅' : '❌')).join(' | ')} |`)
  .join('\n');

const table = [
  head, sep, body, '',
  '✅ keeps the narrowing · ❌ the compiler rejects it — `TS18047: … is possibly \'null\'` on the nullable subjects, `TS2339` on the 5.4 control',
  '',
  `Generated by \`node scripts/run-matrix.mjs\` — last run ${new Date().toISOString().slice(0, 10)}.`,
].join('\n');

const START = '<!-- MATRIX:START -->';
const END = '<!-- MATRIX:END -->';
const readme = readFileSync('README.md', 'utf8');
const next = readme.replace(
  new RegExp(`${START}[\\s\\S]*${END}`),
  `${START}\n\n${table}\n\n${END}`,
);

if (process.argv.includes('--check')) {
  if (next !== readme) {
    console.error('README.md is out of date. Run: node scripts/run-matrix.mjs');
    process.exit(1);
  }
  console.log('README.md matches the measured matrix.');
} else {
  writeFileSync('README.md', next);
  console.log(table);
  console.log('\nREADME.md updated.');
}
